### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by BrianZbr** [iheanyi/bandcamp-dl#1]
I'm consistently getting errors as in the following example:

`Starting the parsing for: http://spark.bandcamp.com/album/eedl-parallemped-ep
Traceback (most recent call last):
  File "bandcamp-dl.py", line 200, in <module>
    parse_file(url)
  File "bandcamp-dl.py", line 80, in parse_file
    stringBlock = jsobj.read_js_object("var TralbumData = %s" % str(stringBlock))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 416: ordinal not in range(128)`

**Comment by andrewmd5** [comment]
5 months late but I resolved this in #2
