### ISSUE TITLE
How do I use this on Windows 8?

### ISSUE THREAD

**Issue by dacomell** [iheanyi/bandcamp-dl#18]
I'm a complete newbie with this, but this script seems to be pretty neat. Can someone publish a "for dummies" step-by-step guide on this??

THANKS!!! :)

**Comment by Bendito999** [comment]
https://github.com/iheanyi/bandcamp-dl/wiki/How-To-Use-%22For-Dummies%22

**Comment by dacomell** [comment]
Thanks bendito!

However, I went through all the steps and ran into an error that says:

Traceback (most recent call last):
   File "bandcamp-dl.py", line 41, in <module>
     from docopt import docopt
Import error: No module named docopt

**Comment by Bendito999** [comment]
From an administrator command prompt, try 

```
pip install docopt
```

What does this return?

You could try this too, but it will probably do the same thing.

```
pip install docopt==0.6.2
```

**Comment by dacomell** [comment]
I found the issue. I had installed python 3.4 and 2.7, and that was creating the issue. I deleted them both and started over. It worked. THANKS!

**Comment by Bendito999** [comment]
Glad it works! Just out of curiosity, is the metadata function working for you (can Windows Media Player detect artists and albums?) If so, were you using my fork or the original? I am just checking that it works the same for others. Thanks!

**Comment by dacomell** [comment]
I used your fork, and it worked like a charm!

Date: Mon, 8 Sep 2014 13:17:53 -0700
